name: morning
on:
  schedule:
  - cron:  '0 0 * * * '
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    name: send morning to your girlfriend

    steps:
    - name: checkout
    - uses: actions/checkout@v2
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
      run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
    - name: morning
      run: |
          python3 main.py
